### PR TITLE
Add additional functions

### PR DESCRIPTION
**Pull request by jurihock**
There are two colorbar functions in matplotlib: `Figure.colorbar` (as already implemented) and `pyplot.colorbar` (proposed in this pr). The `mappable` argument is mandatory in `Figure.colorbar` but optional in `pyplot.colorbar`, which internally defaults to `pyplot.gci`. See also [matplotlib.pyplot.colorbar](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.colorbar.html#matplotlib.pyplot.colorbar).

### CODE REVIEW

**Comment by soblin** [comment]
Hi @jurihock thanks for you PR !
Do you have example codes using these functions ? Or do you know any related examples in this page ?

https://matplotlib.org/stable/gallery/index.html

I want to add them in `gallery/contrib` folder for better coverage if possible.

**Comment by jurihock** [comment]
I plan to use it [here](https://github.com/jurihock/sdft/blob/main/examples/analysis.cpp) instead of the current [matplotlibcpp](https://github.com/lava/matplotlib-cpp) binding. But for that I need at least imshow and clim.

I'm not familiar with xtensor, but [numcpp](https://github.com/dpilger26/NumCpp) works fine to draw a 2D sombrero: 

```c++
#include <matplotlibcpp17/pyplot.h>
#include <NumCpp.hpp>

namespace py = pybind11;

void test()
{
  py::scoped_interpreter guard{};

  const int size = 1000;
  const double sigma = 100;

  const auto i = nc::arange<double>(size) - (0.5 * size);
  const auto [x, y] = nc::meshgrid<double>(i, i);

  const auto xy = (nc::power(x, 2) + nc::power(y, 2)) / (-2.0 * nc::power(sigma, 2));

  const auto sombrero = nc::exp(xy) * (xy + 1.0) / (std::acos(-1.0) * nc::power(sigma, 4));
  const auto pysombrero = nc::pybindInterface::nc2pybind(sombrero);

  auto plot = matplotlibcpp17::pyplot::import();

  plot.imshow(Args(pysombrero), Kwargs(
    "extent"_a = py::make_tuple(-1, +1, -1, +1),
    "cmap"_a = "inferno"));

  plot.colorbar();

  plot.clim(py::make_tuple(-4e-10, +3e-9));

  plot.show();
}
```

sombrero

 Maybe something like that would be a suitable example for the gallery...

**Comment by soblin** [comment]
LGTM.

Then you can rename `test()` to `main()` and  just push that code to `gallery/contrib/sombrero,cpp` without CMakeLists.txt.
Can you tell me the version or current commit hash of your `numcpp` ? Maybe I'll use `numcpp` instead of `xtensor` in the next release.
Also you can add that image to `gallery/contrib/sombrero.png` (maybe you need to `add -f`). Then I will review and merge this PR to latest `main` !

I think I'll add some examples from the official matplotlib gallery using `imshow` and other new functions later. Then I'll release next version.

**Comment by jurihock** [comment]
Okay, thanks!

I'm using the tagged NumCpp 2.8.0 version.

In order to build the provided example you may have to introduce following defines:

```c++
// disable boost
#define NUMCPP_NO_USE_BOOST

// enable nc::pybindInterface::nc2pybind
#define NUMCPP_INCLUDE_PYBIND_PYTHON_INTERFACE
```

**Review by soblin — APPROVED** [review]

**Pull request merged**
